Public Class Constantes
    Public Const regExMontant As String = "^[0-9]+(,[0-9]{0,2})*$"
    Public Const regDateReleve As String = "^[0-3][0-9]/[0-9]{2}/[0-9]{4}"
    Public Const pointVirgule As String = ";"
    Public Const virgule As String = ","
    Public Const espace As String = " "
    Public Const point As String = "."
    Public Const tiret As String = "-"
    Public Const euro As String = " €"
    Public Const plus As String = "+"

    'Requêtes SQL
    '------------
    'Suppressions
    Public Const sqlCptTiers As String = "cptTiers"
    Public Const sqlDelCompte As String = "delCompte"
    Public Const sqlDelDocs As String = "delDocs"
    Public Const sqlDelMvt As String = "delMvt"
    'Insertions
    Public Const sqlInsertChq As String = "insertChq"
    Public Const sqlInsertCompte As String = "insertCompte"
    Public Const sqlInsertDocAgumaaa As String = "insertDocAgumaaa"
    Public Const sqlInsertMvts As String = "insertMvts"
    Public Const sqlinsertTiers As String = "insertTiers"
    'Sélections
    Public Const sqlProcMvtsIdentiques As String = "procMvtsIdentiques"
    Public Const sqlSelCategoriesDefautMouvements As String = "reqCategoriesDefautMouvements"
    Public Const sqlSelCategoriesMouvements As String = "reqCategoriesMouvements"
    Public Const sqlSelChq As String = "reqChq"
    Public Const sqlSelDocs As String = "reqDocs"
    Public Const sqlSelIdentiteCatTiers As String = "reqIdentiteCatTiers"
    Public Const sqlSelIdentiteTiers As String = "reqIdentiteTiers"
    Public Const sqlSelImagesChq As String = "reqImagesChq"
    Public Const sqlSelNbMouvements As String = "reqNbMouvements"
    Public Const sqlSelSommeCatMouvements As String = "reqSommeCatMouvements"
    Public Const sqlSelSousCategoriesDefautMouvements As String = "reqSousCategoriesDefautMouvements"
    Public Const sqlSelTiersMorale As String = "selTiersMorale"
    Public Const sqlSelTiersPhysique As String = "selTiersPhysique"
    Public Const sqlSelSelectMouvementsLibelles As String = "sqlSelectMouvementsLibelles"
    Public Const sqlSelLibCat As String = "reqLibCat"
    'Mises à jour
    Public Const sqlUpdCompte As String = "updCompte"
    Public Const sqlUpdDocs As String = "updDocs"
    Public Const sqlUpdMvt As String = "updMvt"
    Public Const sqlUpdMvtIdChq As String = "updMvtIdChq"

    'Public Const req1 As String = "SELECT distinct catégorie FROM Mouvements ;"
    'Public Const req3 As String = "SELECT sousCatégorie, sum(montant) FROM Mouvements where catégorie = '"
    'Public Const req5 As String = "SELECT DISTINCT catégorie FROM Mouvements;"
    'Public Const req6 As String = "SELECT sousCatégorie, SUM(montant) FROM Mouvements WHERE catégorie = @category GROUP BY sousCatégorie ORDER BY SUM(montant) DESC;"
    'Public Const req7 As String = "SELECT * FROM Mouvements"
    'Public Const req9 As String = "SELECT id, numero, date, emetteur, destinataire FROM Cheque WHERE montant = @montant;"
    'Public Const req10 As String = "SELECT [imageChq] FROM [dbo].Cheque WHERE [id] = @id"
    'Public Const req11 As String = "SELECT idDoc, dateDoc, contenuDoc, cheminDoc, categorieDoc, sousCategorieDoc, idMvtDoc FROM [dbo].[Documents];"
    'Public Const req12 As String = "SELECT id,nom, prenom FROM Tiers where nom is not null;"
    'Public Const req13 As String = "SELECT id,raisonSociale FROM Tiers where raisonSociale is not null;"
    'Public Const req14 As String = "Select file"
    'Public Const req15 As String = "SELECT COUNT(*) FROM Mouvements WHERE dateMvt = @dateMvt AND montant = @montant AND sens = @sens;"
    'Public Const req16 As String = "SELECT id, nom, prenom, raisonSociale, categorieDefaut, sousCategorieDefaut FROM Tiers;"
    'Public Const req17 As String = "SELECT id, libelle FROM Categorie WHERE debit = @debit;"
    'Public Const req18 As String = "SELECT id, libelle FROM SousCategorie where idCategorie = @idCategorie;"
    'Public Const req19 As String = "SELECT libelle FROM SousCategorie where idCategorie ="
    'Public Const req20 As String = "SELECT categorieDefaut FROM Tiers where id = '"
    'Public Const req21 As String = "SELECT sousCategorieDefaut FROM Tiers where id = '"
    'Public Const req22 As String = "SELECT [nom], [prenom], [raisonSociale] FROM [dbo].Tiers"
End Class