'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\categories.ini")>  _
        Public ReadOnly Property ficRessources() As String
            Get
                Return CType(Me("ficRessources"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\tiers.xml")>  _
        Public ReadOnly Property ficTiers() As String
            Get
                Return CType(Me("ficTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gestionTresorerie\Données")>  _
        Public ReadOnly Property repDonnées() As String
            Get
                Return CType(Me("repDonnées"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>SELECT ssCat.libelle, sum(mvt.montant) FROM Mouvements mvt, sousCategorie "& _ 
            "ssCat where ssCat.id = mvt.tabCategorie and mvt.Categorie = '%Id' group by sscat"& _ 
            ".id order by sum(mvt.montant) desc;</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>SELECT evt.libelle, sum("& _ 
            "mvt.montant) FROM Mouvements mvt, Evenements evt where evt.id = mvt.tabCategorie"& _ 
            " and mvt.événement = '%Id' group by événement.id order by événement.id desc;</st"& _ 
            "ring>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public ReadOnly Property Requetes() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Requetes"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\gestionTresorerie.log")>  _
        Public ReadOnly Property fichierLog() As String
            Get
                Return CType(Me("fichierLog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\")>  _
        Public ReadOnly Property repInstallationProd() As String
            Get
                Return CType(Me("repInstallationProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\")>  _
        Public ReadOnly Property repInstallationTest() As String
            Get
                Return CType(Me("repInstallationTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\bddAgumaaa.mdf")>  _
        Public ReadOnly Property bddAgumaaaTest() As String
            Get
                Return CType(Me("bddAgumaaaTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(";Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property ParamDb() As String
            Get
                Return CType(Me("ParamDb"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ficRelevéTraité.txt")>  _
        Public ReadOnly Property ficRelevéTraité() As String
            Get
                Return CType(Me("ficRelevéTraité"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\événement.ini")>  _
        Public ReadOnly Property ficEvénement() As String
            Get
                Return CType(Me("ficEvénement"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\type.ini")>  _
        Public ReadOnly Property ficType() As String
            Get
                Return CType(Me("ficType"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://api.mistral.ai/v1/chat/completions")>  _
        Public ReadOnly Property urlMistral() As String
            Get
                Return CType(Me("urlMistral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources")>  _
        Public ReadOnly Property repFichierBilan() As String
            Get
                Return CType(Me("repFichierBilan"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Mouvements;")>  _
        Public ReadOnly Property reqSelectToutMouvements() As String
            Get
                Return CType(Me("reqSelectToutMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Mouvements WHERE dateMvt = @dateMvt AND montant = @montant A"& _ 
            "ND sens = @sens;")>  _
        Public ReadOnly Property reqNbMouvements() As String
            Get
                Return CType(Me("reqNbMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT [imageChq] FROM [dbo].Cheque WHERE [id] = @id")>  _
        Public ReadOnly Property reqImagesChq() As String
            Get
                Return CType(Me("reqImagesChq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT [nom], [prenom], [raisonSociale] FROM [dbo].Tiers")>  _
        Public ReadOnly Property reqIdentiteTiers() As String
            Get
                Return CType(Me("reqIdentiteTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM Categorie WHERE debit = @debit;")>  _
        Public ReadOnly Property reqCategorie() As String
            Get
                Return CType(Me("reqCategorie"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM SousCategorie where idCategorie = @idCategorie;")>  _
        Public ReadOnly Property reqSousCategorie() As String
            Get
                Return CType(Me("reqSousCategorie"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT libelle FROM SousCategorie where idCategorie =")>  _
        Public ReadOnly Property reqLibelleSousCategorie() As String
            Get
                Return CType(Me("reqLibelleSousCategorie"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EXEC dbo.ObtenirMouvementsSimilaires @dateMvt, @montant, @sens")>  _
        Public ReadOnly Property procMvtsIdentiquesEX() As String
            Get
                Return CType(Me("procMvtsIdentiquesEX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gestionTresorerie\monFichier.docx")>  _
        Public ReadOnly Property ficBilan() As String
            Get
                Return CType(Me("ficBilan"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Mouvements SET idDoc = @nouvelIdDoc WHERE Id = @idMouvement")>  _
        Public ReadOnly Property updMvtIdDoc() As String
            Get
                Return CType(Me("updMvtIdDoc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM Categorie")>  _
        Public ReadOnly Property reqCategorieTout() As String
            Get
                Return CType(Me("reqCategorieTout"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM Categorie;")>  _
        Public ReadOnly Property selIdLibCat() As String
            Get
                Return CType(Me("selIdLibCat"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Mouvements] WHERE [Id] = @Id")>  _
        Public ReadOnly Property delMvt() As String
            Get
                Return CType(Me("delMvt"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Comptes] WHERE [login] = @login")>  _
        Public ReadOnly Property delCompte() As String
            Get
                Return CType(Me("delCompte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Comptes] SET [motDePasse] = @motDePasse WHERE [login] = @login")>  _
        Public ReadOnly Property updCompte() As String
            Get
                Return CType(Me("updCompte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Comptes] ([login], [motDePasse], [typeAcces]) VALUES (@login, "& _ 
            "@motDePasse, @typeAcces)")>  _
        Public ReadOnly Property insertCompte() As String
            Get
                Return CType(Me("insertCompte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].Cheque ([numero], [date], [emetteur], [montant], [banque], [des"& _ 
            "tinataire], [imageChq]) VALUES (@numero, @date, @emetteur, @montant, @banque, @d"& _ 
            "estinataire, @imageChq);")>  _
        Public ReadOnly Property insertChq() As String
            Get
                Return CType(Me("insertChq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Documents] WHERE idDoc = @idDoc"&Global.Microsoft.VisualBasic.ChrW(9)&";")>  _
        Public ReadOnly Property delDocs() As String
            Get
                Return CType(Me("delDocs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Tiers WHERE (nom = @nom AND prenom = @prenom and raisonSocia"& _ 
            "le is null) OR raisonSociale = @raisonSociale and nom is null AND prenom is null"& _ 
            ";")>  _
        Public ReadOnly Property cptTiers() As String
            Get
                Return CType(Me("cptTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Tiers WHERE (nom = @nom AND prenom = @prenom) OR raisonSocia"& _ 
            "le = @raisonSociale);")>  _
        Public ReadOnly Property selExisteTiers() As String
            Get
                Return CType(Me("selExisteTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO Tiers (nom, prenom, raisonSociale, categorieDefaut, sousCategorieDefa"& _ 
            "ut, dateCreation, dateModification) VALUES (@nom, @prenom, @raisonSociale, @cate"& _ 
            "gorieDefaut, @sousCategorieDefaut, @dateCreation, @dateModification);SELECT SCOP"& _ 
            "E_IDENTITY();")>  _
        Public ReadOnly Property insertTiers() As String
            Get
                Return CType(Me("insertTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("parametresAppli.json")>  _
        Public ReadOnly Property parametresJson() As String
            Get
                Return CType(Me("parametresJson"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT libelle FROM Categorie where Id = @id")>  _
        Public ReadOnly Property reqLibCat() As String
            Get
                Return CType(Me("reqLibCat"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("uswXFN4VPYfYmrTmNbLY16D3fxFunwjm")>  _
        Public ReadOnly Property cleApiMistral() As String
            Get
                Return CType(Me("cleApiMistral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("pixtral-12b-2409")>  _
        Public ReadOnly Property modeleMistral() As String
            Get
                Return CType(Me("modeleMistral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select id, libelle from TypeMouvement;")>  _
        Public ReadOnly Property reqTypesMouvement() As String
            Get
                Return CType(Me("reqTypesMouvement"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select id, libelle from Evenement;")>  _
        Public ReadOnly Property reqEvenement() As String
            Get
                Return CType(Me("reqEvenement"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INFO")>  _
        Public ReadOnly Property niveauLog() As String
            Get
                Return CType(Me("niveauLog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM SousCategorie;")>  _
        Public ReadOnly Property sqlSelSousCategoriesTout() As String
            Get
                Return CType(Me("sqlSelSousCategoriesTout"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("""FRAIS Commission : Virement emis;FRAIS Tenue de compte professionnel : Virement "& _ 
            "emis;FRAIS saisie administrative : Virement emis;INTERETS CREDITEURS C.L.ALLEGRE"& _ 
            " : Virement recu ;PRELEVEMENT AIST : Prelevement;PRELEVEMENT GIE KLESIA COTIS : "& _ 
            "Prelevement;PRELEVEMENT HUMANIS PREVOYANCE PLEIADE : Prelevement;PRELEVEMENT KOE"& _ 
            "SIO AURA : Prelevement;PRELEVEMENT Relevé de compte quinzaine : Prelevement;PREL"& _ 
            "EVEMENT URSSAF AUVERGNE : Prelevement;REMISE DE CHEQUE;SOUSCRIPTION C.L.ALLEGRE "& _ 
            ": Prelevement;VERSEMENT D'ESPECES ALLEGRE : Depot especes;VIREMENT EMIS BLOCAGE "& _ 
            "SAISIE ADMIN A TIERS DET ;VIREMENT EMIS WEB A G U M A A : Depot especes;VIREMENT"& _ 
            " EN VOTRE FAVEUR : Virement recu ;PRELEVEMENT AIST 43 : Prelevement;PRELEVEMENT "& _ 
            "URSSAF D AUVERGNE : Prelevement;RETRAIT D'ESPECES : Especes;PRELEVEMENT ;SACEMSO"& _ 
            "C AUTEUR COMPOSITEUR : Prelevement;RETRO A TITRE COMMERCIAL : Virement recu ;VIR"& _ 
            "EMENT EMIS SY SERVICE IMPOTS DES ENTRE : Virement emis;VIREMENT EMIS WEB A G U M"& _ 
            " A A Alimentation : Virement emis""")>  _
        Public ReadOnly Property dicoTypeMvt() As String
            Get
                Return CType(Me("dicoTypeMvt"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA")>  _
        Public Property repRacineAgumaaa() As String
            Get
                Return CType(Me("repRacineAgumaaa"),String)
            End Get
            Set
                Me("repRacineAgumaaa") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\Documents\Agumaaa\Trésorerie\bddAgumaaaProd2.mdf")>  _
        Public ReadOnly Property bddAgumaaaProd() As String
            Get
                Return CType(Me("bddAgumaaaProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Gestion\Trésorerie\Comptabilité\Bdd\bddAgumaaaProd2.mdf")>  _
        Public ReadOnly Property copieMdbGoogleDrive() As String
            Get
                Return CType(Me("copieMdbGoogleDrive"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("A_Trier")>  _
        Public ReadOnly Property repFichiersDocumentsATrier() As String
            Get
                Return CType(Me("repFichiersDocumentsATrier"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Chèques")>  _
        Public ReadOnly Property repFichiersDocumentsChèques() As String
            Get
                Return CType(Me("repFichiersDocumentsChèques"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Manifestations récurrentes\Activités\Gym")>  _
        Public ReadOnly Property repFichiersGym() As String
            Get
                Return CType(Me("repFichiersGym"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Formulaires d'adhésion")>  _
        Public ReadOnly Property repGymAdhésion() As String
            Get
                Return CType(Me("repGymAdhésion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("QuestionnairesSanté")>  _
        Public ReadOnly Property repGymQuestionnaire() As String
            Get
                Return CType(Me("repGymQuestionnaire"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Documents")>  _
        Public ReadOnly Property repRacineDocuments() As String
            Get
                Return CType(Me("repRacineDocuments"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Gestion\Trésorerie\Comptabilité\Eléments comptables")>  _
        Public ReadOnly Property repRacineComptabilité() As String
            Get
                Return CType(Me("repRacineComptabilité"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Manifestations récurrentes\Marché de Noël")>  _
        Public ReadOnly Property repRacineMdN() As String
            Get
                Return CType(Me("repRacineMdN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Administratif\attestationsNonParticipationAutresMarches")>  _
        Public ReadOnly Property repAttestationsNonParticipationAutresMarches() As String
            Get
                Return CType(Me("repAttestationsNonParticipationAutresMarches"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Factures")>  _
        Public ReadOnly Property repFichiersDocumentsFactures() As String
            Get
                Return CType(Me("repFichiersDocumentsFactures"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Emises")>  _
        Public ReadOnly Property repFichiersFacturesEmises() As String
            Get
                Return CType(Me("repFichiersFacturesEmises"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Recues")>  _
        Public ReadOnly Property repFichiersFacturesRecues() As String
            Get
                Return CType(Me("repFichiersFacturesRecues"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT prompt, gabaritRepertoire, gabaritNomFichier, classe FROM TypeDoc;")>  _
        Public ReadOnly Property sqlTypesDocuments() As String
            Get
                Return CType(Me("sqlTypesDocuments"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT libellé FROM TypeDoc;")>  _
        Public ReadOnly Property reqLibellesTypesDocuments() As String
            Get
                Return CType(Me("reqLibellesTypesDocuments"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT idDoc, dateDoc, contenuDoc, cheminDoc, categorieDoc, sousCategorieDoc, idM"& _ 
            "vtDoc, metaDonnees FROM [dbo].[Documents];")>  _
        Public ReadOnly Property reqDocs() As String
            Get
                Return CType(Me("reqDocs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Documents] SET dateDoc = @dateDoc, contenuDoc = @contenuDoc, chemin"& _ 
            "Doc = @cheminDoc, categorieDoc = @categorieDoc, sousCategorieDoc = @sousCategori"& _ 
            "eDoc, idMvtDoc=@idMvtDoc, metaDonnees=@metaDonnees WHERE idDoc = @idDoc;")>  _
        Public ReadOnly Property updDocs() As String
            Get
                Return CType(Me("updDocs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Documents] (dateDoc, contenuDoc, cheminDoc, categorieDoc, sous"& _ 
            "CategorieDoc, idMvtDoc, metaDonnees) VALUES (@dateDoc, @contenuDoc, @cheminDoc, "& _ 
            "@categorieDoc, @sousCategorieDoc, @idMvtDoc, @metaDonnees);")>  _
        Public ReadOnly Property insertDocAgumaaa() As String
            Get
                Return CType(Me("insertDocAgumaaa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://drive.google.com/drive/folders/1yxfwBMp-bwpMHqMZZd5fHWcAhkZnH7F6?usp=driv"& _ 
            "e_link")>  _
        Public ReadOnly Property urlRacinedriveAgumaaa() As String
            Get
                Return CType(Me("urlRacinedriveAgumaaa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\Downloads\CRBatch.json")>  _
        Public ReadOnly Property fichierCRBatch() As String
            Get
                Return CType(Me("fichierCRBatch"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Gestion\Trésorerie\Comptabilité\Eléments comptables\Chèques\"& _ 
            "")>  _
        Public ReadOnly Property repChqProd() As String
            Get
                Return CType(Me("repChqProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\lstTiers.csv")>  _
        Public ReadOnly Property ficLstTiers() As String
            Get
                Return CType(Me("ficLstTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT libellé FROM TypeDoc;")>  _
        Public ReadOnly Property sqlLibellesTypesDocuments() As String
            Get
                Return CType(Me("sqlLibellesTypesDocuments"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, numero, date, emetteur, destinataire FROM Cheque WHERE montant = @mont"& _ 
            "ant;")>  _
        Public ReadOnly Property reqChq() As String
            Get
                Return CType(Me("reqChq"),String)
            End Get
        End Property
        
        '''<summary>
        '''Procécdure stockée d&apos;identification des mouvements déjà saisis
        '''</summary>
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Procécdure stockée d'identification des mouvements déjà saisis"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Id, categorie, sousCategorie, montant, sens, tiers, note, dateMvt, dateCre"& _ 
            "ation, dateModification, etat, evenement, typeMouvement, modifiable, numeroRemis"& _ 
            "e, reference, typeReference, idDoc FROM [dbo].[Mouvements] WHERE dateMvt = @date"& _ 
            "Mvt AND montant = @montant AND sens = @sens;")>  _
        Public ReadOnly Property procMvtsIdentiques() As String
            Get
                Return CType(Me("procMvtsIdentiques"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Mouvements] (note, categorie, sousCategorie, tiers, dateCreati"& _ 
            "on, dateMvt, montant, sens, etat, evenement, typeMouvement, modifiable, numeroRe"& _ 
            "mise, reference, typeReference, idDoc) VALUES (@note, @categorie, @sousCategorie"& _ 
            ", @tiers, @dateCreation, @dateMvt, @montant, @sens, @etat, @evenement, @typeMouv"& _ 
            "ement, @modifiable, @numeroRemise, @reference, @typeReference, @idDoc);")>  _
        Public ReadOnly Property insertMvts() As String
            Get
                Return CType(Me("insertMvts"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT idDoc, dateDoc, contenuDoc, cheminDoc, categorieDoc, sousCategorieDoc, idM"& _ 
            "vtDoc, metaDonnees, dateModif  FROM Documents WHERE JSON_VALUE(metaDonnees, '$.n"& _ 
            "umero_du_cheque') IS NOT NULL  AND JSON_VALUE(metaDonnees, '$.numero_du_cheque')"& _ 
            " = @numero  AND JSON_VALUE(metaDonnees, '$.montant_numerique') = @montant  AND J"& _ 
            "SON_VALUE(metaDonnees, '$.emetteur_du_cheque') like @emetteur;")>  _
        Public ReadOnly Property reqDoc() As String
            Get
                Return CType(Me("reqDoc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Documents SET metaDonnees = @metaDonnees, dateModif = GETDATE() WHERE IdDo"& _ 
            "c = @idDocument;")>  _
        Public ReadOnly Property updateDocumentMetaDonnees() As String
            Get
                Return CType(Me("updateDocumentMetaDonnees"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO Utilisateurs (NomUtilisateur, MotDePasse, Role, Actif) VALUES (@nom, "& _ 
            "@pwd, @role, @actif);")>  _
        Public ReadOnly Property insertUtilisateur() As String
            Get
                Return CType(Me("insertUtilisateur"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Utilisateurs SET NomUtilisateur = @nom, Role = @role, Actif = @actif, MotD"& _ 
            "ePasse = ISNULL(@pwd, MotDePasse) WHERE Id = @id;")>  _
        Public ReadOnly Property updUtilisateur() As String
            Get
                Return CType(Me("updUtilisateur"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Utilisateurs SET Actif = @actif WHERE Id = @id;")>  _
        Public ReadOnly Property updDesactiveUtilisateur() As String
            Get
                Return CType(Me("updDesactiveUtilisateur"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Utilisateurs SET MotDePasse = @pwd WHERE Id = @id;")>  _
        Public ReadOnly Property updMdPUtilisateur() As String
            Get
                Return CType(Me("updMdPUtilisateur"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT idDoc, dateDoc, contenuDoc, cheminDoc, categorieDoc, sousCategorieDoc, idM"& _ 
            "vtDoc, metaDonnees, dateModif  FROM Documents WHERE JSON_VALUE(metaDonnees, '$.m"& _ 
            "ontant_numerique') = @montant;")>  _
        Public ReadOnly Property reqDocMontant() As String
            Get
                Return CType(Me("reqDocMontant"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\mistral_state.json")>  _
        Public ReadOnly Property ficAgentMistral() As String
            Get
                Return CType(Me("ficAgentMistral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Documents SET cheminDoc = @cheminDoc WHERE idDoc = @idDoc;")>  _
        Public ReadOnly Property updCheminDoc() As String
            Get
                Return CType(Me("updCheminDoc"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Documents  ;")>  _
        Public ReadOnly Property cptDocPagination() As String
            Get
                Return CType(Me("cptDocPagination"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT idDoc, dateDoc, cheminDoc, categorieDoc, sousCategorieDoc, idMvtDoc, metaD"& _ 
            "onnees, dateModif  FROM Documents ORDER BY dateDoc desc OFFSET @Offset ROWS FETC"& _ 
            "H NEXT @TaillePage ROWS ONLY;")>  _
        Public ReadOnly Property selDocPagination() As String
            Get
                Return CType(Me("selDocPagination"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\Documents\Cinéma\Entrées\EntréesCinéma2025.xlsx")>  _
        Public ReadOnly Property fichierEntreesCinemaExcel() As String
            Get
                Return CType(Me("fichierEntreesCinemaExcel"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO Films(Titre, DureeMinutes, Genre, Realisateur, DateSortie, Synopsis, "& _ 
            "AgeMinimum, AfficheUrl) VALUES (@Titre, @DureeMinutes, @Genre, @Realisateur, @Da"& _ 
            "teSortie, @Synopsis, @AgeMinimum, @AfficheUrl);SELECT CAST(SCOPE_IDENTITY() AS I"& _ 
            "NT);")>  _
        Public ReadOnly Property insertFilm() As String
            Get
                Return CType(Me("insertFilm"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO Seances(IdFilm, DateHeureDebut, TarifBase, Langue, Format, NbEntreesA"& _ 
            "dultes, NbEntreesEnfants, NbEntreesGroupeEnfants) VALUES (@IdFilm, @DateHeureDeb"& _ 
            "ut, @TarifBase, @Langue, @Format, @NbEntreesAdultes, @NbEntreesEnfants, @NbEntre"& _ 
            "esGroupeEnfants);")>  _
        Public ReadOnly Property insertSeance() As String
            Get
                Return CType(Me("insertSeance"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Films where Titre=@titre")>  _
        Public ReadOnly Property selFilmParTitre() As String
            Get
                Return CType(Me("selFilmParTitre"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM Films WHERE IdFilm=@Id")>  _
        Public ReadOnly Property delFilm() As String
            Get
                Return CType(Me("delFilm"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM Seances WHERE IdSeance=@Id")>  _
        Public ReadOnly Property delSeance() As String
            Get
                Return CType(Me("delSeance"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Seances WHERE IdFilm=@IdFilm ORDER BY DateHeureDebut")>  _
        Public ReadOnly Property selSeanceIdFilm() As String
            Get
                Return CType(Me("selSeanceIdFilm"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\OneDrive\Documents\CinemaDB.mdf")>  _
        Public Property cinemaDBProd() As String
            Get
                Return CType(Me("cinemaDBProd"),String)
            End Get
            Set
                Me("cinemaDBProd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\OneDrive\Documents\CinemaDBTest.mdf")>  _
        Public Property cinemaDBTest() As String
            Get
                Return CType(Me("cinemaDBTest"),String)
            End Get
            Set
                Me("cinemaDBTest") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT TOP 10 * FROM vStatsParFilm ORDER BY CA_Total DESC;")>  _
        Public ReadOnly Property sel10Stat() As String
            Get
                Return CType(Me("sel10Stat"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vStatsParFilm;")>  _
        Public ReadOnly Property selStatsParFilm() As String
            Get
                Return CType(Me("selStatsParFilm"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vStatsParMois;")>  _
        Public ReadOnly Property selStatsParMois() As String
            Get
                Return CType(Me("selStatsParMois"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM vStatistiquesSeances;")>  _
        Public Property selSeancesAvecFilm() As String
            Get
                Return CType(Me("selSeancesAvecFilm"),String)
            End Get
            Set
                Me("selSeancesAvecFilm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select * from tarifs;")>  _
        Public Property selTarifsValides() As String
            Get
                Return CType(Me("selTarifsValides"),String)
            End Get
            Set
                Me("selTarifsValides") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("d4371f28c29f00bf2c168bd709a26059")>  _
        Public ReadOnly Property cleApiTmdb() As String
            Get
                Return CType(Me("cleApiTmdb"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkNDM3MWYyOGMyOWYwMGJmMmMxNjhiZDcwOWEyNjA1OSIsIm5i"& _ 
            "ZiI6MTY0NDA3ODkzMS41OTEsInN1YiI6IjYxZmVhNzUzMzg0NjlhMDAxY2FhOTYwOCIsInNjb3BlcyI6"& _ 
            "WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Sf5hUzafWHm_MlfHRFKKOATpBIBst5AOWFDqwHwk344")>  _
        Public ReadOnly Property jetonApiTmdb() As String
            Get
                Return CType(Me("jetonApiTmdb"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT TitreFilm FROM Seances;")>  _
        Public ReadOnly Property selListeFilms() As String
            Get
                Return CType(Me("selListeFilms"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Films WHERE Titre=@Titre")>  _
        Public ReadOnly Property selTitreFilm() As String
            Get
                Return CType(Me("selTitreFilm"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Titre FROM Films WHERE IdFilm = @IdFilm")>  _
        Public ReadOnly Property selTitreFilmParId() As String
            Get
                Return CType(Me("selTitreFilmParId"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\gestionTresorerie\Resources\logoAgum"& _ 
            "aaa.png")>  _
        Public ReadOnly Property logoAgumaaa() As String
            Get
                Return CType(Me("logoAgumaaa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\gestionTresorerie\Resources\logoCine"& _ 
            "ma.png")>  _
        Public ReadOnly Property logoCinema() As String
            Get
                Return CType(Me("logoCinema"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\Downloads\programme.docx")>  _
        Public ReadOnly Property cheminProgramme() As String
            Get
                Return CType(Me("cheminProgramme"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\gestionTresorerie\Resources\logoCine"& _ 
            "vasion.png")>  _
        Public ReadOnly Property logoCinevasion() As String
            Get
                Return CType(Me("logoCinevasion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO dbo.ParticipantMdN (Nom, Prenom, RaisonSociale, Activite, Adresse, CP"& _ 
            ", Ville, Grille, Tables, DateCourrier, Paiement, Siret, Tel, Mail, Type, Sexe, P"& _ 
            "ieceIdentite, DateNaissance, LieuNaissance) VALUES (@Nom, @Prenom, @RaisonSocial"& _ 
            "e, @Activite, @Adresse, @CP, @Ville, @Grille, @Tables, @DateCourrier, @Paiement,"& _ 
            " @Siret, @Tel, @Mail, @Type, @Sexe, @PieceIdentite, @DateNaissance, @LieuNaissan"& _ 
            "ce);")>  _
        Public ReadOnly Property insertParticipantMdN() As String
            Get
                Return CType(Me("insertParticipantMdN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\Manifestations récurrentes\Marché de Noël\2025\Adm"& _ 
            "inistratif\attestationsNonParticipationAutresMarches")>  _
        Public ReadOnly Property repAttNonParticipation() As String
            Get
                Return CType(Me("repAttNonParticipation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT IdParticipant, Nom, Prenom, RaisonSociale, Activite, Adresse, CP, Ville, G"& _ 
            "rille, Tables, DateCourrier, Paiement, Siret, Tel, Mail, Type, Sexe, PieceIdenti"& _ 
            "te, DateNaissance, LieuNaissance FROM dbo.ParticipantMdN ORDER BY Nom, Prenom;")>  _
        Public ReadOnly Property selParticipant() As String
            Get
                Return CType(Me("selParticipant"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\Manifestations récurrentes\Marché de Noël\2025\Adm"& _ 
            "inistratif\attestationsNonParticipationAutresMarches\AttestationNonParticipation"& _ 
            "DeuxAutresmarchés.docx")>  _
        Public ReadOnly Property modeleAttestationNonParticipation() As String
            Get
                Return CType(Me("modeleAttestationNonParticipation"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\USERS\USER\ONEDRIVE\DOCUMENTS\MARCHEDENOELDB.MDF")>  _
        Public Property marcheDeNoelDBProd() As String
            Get
                Return CType(Me("marcheDeNoelDBProd"),String)
            End Get
            Set
                Me("marcheDeNoelDBProd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\USERS\USER\ONEDRIVE\DOCUMENTS\MARCHEDENOELDBTest.MDF")>  _
        Public Property marcheDeNoelDBTest() As String
            Get
                Return CType(Me("marcheDeNoelDBTest"),String)
            End Get
            Set
                Me("marcheDeNoelDBTest") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public ReadOnly Property SMTP_Server() As String
            Get
                Return CType(Me("SMTP_Server"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public ReadOnly Property SMTP_Port() As String
            Get
                Return CType(Me("SMTP_Port"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("agumaaa43@gmail.com")>  _
        Public ReadOnly Property SMTP_User() As String
            Get
                Return CType(Me("SMTP_User"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("agumaaa43@gmail.com")>  _
        Public ReadOnly Property SmtpUsername() As String
            Get
                Return CType(Me("SmtpUsername"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public ReadOnly Property SmtpServer() As String
            Get
                Return CType(Me("SmtpServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("587")>  _
        Public ReadOnly Property SmtpPort() As String
            Get
                Return CType(Me("SmtpPort"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\Downloads\gestionTresorerie_20251120\gestionTresorerie\gestionTreso"& _ 
            "rerie\Resources\ModeleMailAttestation.html")>  _
        Public Property repModeleBodyAttHtml() As String
            Get
                Return CType(Me("repModeleBodyAttHtml"),String)
            End Get
            Set
                Me("repModeleBodyAttHtml") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT 1 FROM Coordonnees WHERE IdTiers = @IdTiers;")>  _
        Public ReadOnly Property existeCoordonnee() As String
            Get
                Return CType(Me("existeCoordonnee"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, nom, prenom, raisonSociale, categorieDefaut, sousCategorieDefaut FROM "& _ 
            "Tiers;")>  _
        Public ReadOnly Property reqIdentiteCatTiers() As String
            Get
                Return CType(Me("reqIdentiteCatTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT nom, prenom, raisonSociale, Email FROM Tiers t, Coordonnees c where c.IdTi"& _ 
            "ers = t.Id;")>  _
        Public ReadOnly Property reqIdentiteCoordonnees() As String
            Get
                Return CType(Me("reqIdentiteCoordonnees"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id,nom, prenom FROM Tiers where nom is not null;")>  _
        Public ReadOnly Property reqIdentitePPTiers() As String
            Get
                Return CType(Me("reqIdentitePPTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id,raisonSociale FROM Tiers where raisonSociale is not null;")>  _
        Public ReadOnly Property reqIdentitePMTiers() As String
            Get
                Return CType(Me("reqIdentitePMTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, nom, prenom FROM Tiers WHERE nom IS NOT NULL;")>  _
        Public ReadOnly Property selTiersPhysique() As String
            Get
                Return CType(Me("selTiersPhysique"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, raisonSociale FROM Tiers WHERE raisonSociale IS NOT NULL;")>  _
        Public ReadOnly Property selTiersMorale() As String
            Get
                Return CType(Me("selTiersMorale"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT sousCategorieDefaut FROM Tiers where id = @id;")>  _
        Public ReadOnly Property reqSousCategoriesDefautMouvements() As String
            Get
                Return CType(Me("reqSousCategoriesDefautMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT categorieDefaut FROM Tiers where id = @id")>  _
        Public ReadOnly Property reqCategoriesDefautMouvements() As String
            Get
                Return CType(Me("reqCategoriesDefautMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT NomCommune FROM Communes WHERE CodePostal = @CodePostal ORDER BY "& _ 
            "NomCommune;")>  _
        Public ReadOnly Property selVillesParCP() As String
            Get
                Return CType(Me("selVillesParCP"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Coordonnees SET Rue1 = @Rue1, Rue2 = @Rue2, CodePostal = @CodePostal, Vill"& _ 
            "e = @Ville, Pays = @Pays, Email = @Email, Telephone = @Telephone WHERE IdTiers ="& _ 
            " @IdTiers;")>  _
        Public ReadOnly Property updateCoordonnees() As String
            Get
                Return CType(Me("updateCoordonnees"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO Coordonnees (IdTiers, Rue1, Rue2, CodePostal, Ville, Pays, Email, Tel"& _ 
            "ephone) VALUES (@IdTiers, @Rue1, @Rue2, @CodePostal, @Ville, @Pays, @Email, @Tel"& _ 
            "ephone);"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"SELECT SCOPE_IDENTITY();")>  _
        Public ReadOnly Property insertCoordonnees() As String
            Get
                Return CType(Me("insertCoordonnees"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Id, IdTiers, Rue1, Rue2, CodePostal, Ville, Pays, Email, Telephone FROM Co"& _ 
            "ordonnees WHERE IdTiers = @IdTiers ORDER BY CodePostal DESC, Id ASC;")>  _
        Public ReadOnly Property selCoordonneesByIdTiers() As String
            Get
                Return CType(Me("selCoordonneesByIdTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE AdherantsGym SET DateMiseAJourLicence = @dateMaj, LicenceId = @licenceId  "& _ 
            "WHERE IdTiers = IdTiers;")>  _
        Public ReadOnly Property updDateMajLicence() As String
            Get
                Return CType(Me("updDateMajLicence"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT TOP 1 Id FROM dbo.Tiers WHERE (@nom IS NULL OR UPPER(LTRIM(RTRIM(nom))) = "& _ 
            "UPPER(LTRIM(RTRIM(@nom)))) AND (@prenom IS NULL OR UPPER(LTRIM(RTRIM(prenom))) ="& _ 
            " UPPER(LTRIM(RTRIM(@prenom)))) AND (@dateNaissance IS NULL OR CAST(dateNaissance"& _ 
            " AS DATE) = @dateNaissance);")>  _
        Public ReadOnly Property getIdTiersByNomPrenomDate() As String
            Get
                Return CType(Me("getIdTiersByNomPrenomDate"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT sousCategorie, sum(montant) FROM Mouvements where categorie = @categorie")>  _
        Public ReadOnly Property reqSommeSousCatMouvements() As String
            Get
                Return CType(Me("reqSommeSousCatMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Mouvements] SET [categorie] = @Categorie, [sousCategorie] = @SousCa"& _ 
            "tegorie, [tiers] = @Tiers, [note] = @Note, [dateModification] = GETDATE(), [etat"& _ 
            "] = @Etat, [evenement] = @Evenement, [typeMouvement] = @TypeMouvement, [modifiab"& _ 
            "le] = @Modifiable, [numeroRemise] = @NumeroRemise where [Id] = @Id")>  _
        Public ReadOnly Property updMvt() As String
            Get
                Return CType(Me("updMvt"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT categorie FROM Mouvements;")>  _
        Public ReadOnly Property reqCategoriesMouvements() As String
            Get
                Return CType(Me("reqCategoriesMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT libelle from categorie where id in (select categorie FROM Mouveme"& _ 
            "nts);")>  _
        Public ReadOnly Property reqCategoriesMouvementsOld() As String
            Get
                Return CType(Me("reqCategoriesMouvementsOld"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("with sel as (SELECT distinct sousCategorie as sousCat, SUM(montant) as mnt FROM M"& _ 
            "ouvements Mvt WHERE Mvt.categorie = @categorie group by sousCategorie) select sC"& _ 
            ".libelle, mnt from sel, sousCategorie sC where sC.id = sousCat;")>  _
        Public ReadOnly Property reqSommeCatMouvements() As String
            Get
                Return CType(Me("reqSommeCatMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select Id , categorie, sousCategorie, montant , sens , tiers , note , dateMvt , d"& _ 
            "ateCreation , dateModification , etat , evenement , typeMouvement , modifiable, "& _ 
            "numeroRemise, reference, typeReference, idDoc from Mouvements;")>  _
        Public ReadOnly Property sqlSelectMouvements() As String
            Get
                Return CType(Me("sqlSelectMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select Id , (select libelle from Categorie where id = categorie) as Categorie, (s"& _ 
            "elect libelle from sousCategorie where id = sousCategorie) as sousCategorie, mon"& _ 
            "tant , CASE sens WHEN 1 THEN 'Crédit' ELSE 'Débit' END as 'Sens', (select coales"& _ 
            "ce(nom + ' ' + prenom, raisonSociale ) from Tiers where id = tiers) as Tiers, no"& _ 
            "te, dateMvt, dateCreation, dateModification, etat, evenement, typeMouvement, CAS"& _ 
            "E modifiable WHEN 1 THEN 'modifiable' ELSE 'Non modifiable' END as 'Modifiable',"& _ 
            " numeroRemise, reference, typeReference, idDoc from Mouvements;")>  _
        Public ReadOnly Property sqlSelectMouvementsLibelles() As String
            Get
                Return CType(Me("sqlSelectMouvementsLibelles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Id, categorie, sousCategorie, montant, sens, tiers, note, dateMvt, dateCre"& _ 
            "ation, dateModification, etat, evenement, typeMouvement, modifiable, numeroRemis"& _ 
            "e, reference, typeReference, idDoc FROM [dbo].[Mouvements] WHERE dateMvt = @date"& _ 
            "Mvt AND montant = @montant AND sens = @sens;")>  _
        Public ReadOnly Property reqMouvementsSimilaires() As String
            Get
                Return CType(Me("reqMouvementsSimilaires"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;   ")>  _
        Public ReadOnly Property DataSoure() As String
            Get
                Return CType(Me("DataSoure"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Initial Catalog=bddAgumaaaProd2;")>  _
        Public ReadOnly Property InitialCatalog() As String
            Get
                Return CType(Me("InitialCatalog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Integrated Security=True;")>  _
        Public ReadOnly Property IntegratedSecurity() As String
            Get
                Return CType(Me("IntegratedSecurity"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MultipleActiveResultSets=False;")>  _
        Public ReadOnly Property MultipleActiveResultSets() As String
            Get
                Return CType(Me("MultipleActiveResultSets"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Connect Timeout=30")>  _
        Public ReadOnly Property ConnectTimeout() As String
            Get
                Return CType(Me("ConnectTimeout"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB; Initial Catalog=bddAgumaaaProd2;Integrated Se"& _ 
            "curity=True;MultipleActiveResultSets=True;Connect Timeout=30")>  _
        Public Property connectionString() As String
            Get
                Return CType(Me("connectionString"),String)
            End Get
            Set
                Me("connectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\SQLDATA\")>  _
        Public ReadOnly Property dossierDestinationExportData() As String
            Get
                Return CType(Me("dossierDestinationExportData"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("01237705000")>  _
        Public ReadOnly Property numCptAgumaaa() As String
            Get
                Return CType(Me("numCptAgumaaa"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.gestionTresorerie.My.MySettings
            Get
                Return Global.gestionTresorerie.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
