'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\categories.ini")>  _
        Public ReadOnly Property ficRessources() As String
            Get
                Return CType(Me("ficRessources"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\tiers.xml")>  _
        Public ReadOnly Property ficTiers() As String
            Get
                Return CType(Me("ficTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gestionTresorerie\Données")>  _
        Public ReadOnly Property repDonnées() As String
            Get
                Return CType(Me("repDonnées"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsd=""http://www.w3."& _ 
            "org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <s"& _ 
            "tring>SELECT ssCat.libelle, sum(mvt.montant) FROM Mouvements mvt, sousCategorie "& _ 
            "ssCat where ssCat.id = mvt.tabCategorie and mvt.Categorie = '%Id' group by sscat"& _ 
            ".id order by sum(mvt.montant) desc;</string>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string>SELECT evt.libelle, sum("& _ 
            "mvt.montant) FROM Mouvements mvt, Evenements evt where evt.id = mvt.tabCategorie"& _ 
            " and mvt.événement = '%Id' group by événement.id order by événement.id desc;</st"& _ 
            "ring>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"  <string />"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"</ArrayOfString>")>  _
        Public ReadOnly Property Requetes() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("Requetes"),Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""G:\Mon Drive\AGUMAAA\Documen"& _ 
            "ts\BacASable\bddAgumaaa.mdf"";Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property DBsource() As String
            Get
                Return CType(Me("DBsource"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\gestionTresorerie.log")>  _
        Public ReadOnly Property fichierLog() As String
            Get
                Return CType(Me("fichierLog"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\")>  _
        Public ReadOnly Property repInstallationProd() As String
            Get
                Return CType(Me("repInstallationProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Users\User\source\repos\gestionTresorerie\")>  _
        Public ReadOnly Property repInstallationTest() As String
            Get
                Return CType(Me("repInstallationTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\bddAgumaaa.mdf")>  _
        Public ReadOnly Property ficBddDonnees() As String
            Get
                Return CType(Me("ficBddDonnees"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""G:\Mon Drive\AGUMAAA\Documen"& _ 
            "ts\BacASable\bddAgumaaa.mdf"";Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property DBsourceProd() As String
            Get
                Return CType(Me("DBsourceProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=""G:\Mon Drive\AGUMAAA\Documen"& _ 
            "ts\BacASable\bddAgumaaa.mdf"";Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property DBsourceTest() As String
            Get
                Return CType(Me("DBsourceTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\bddAgumaaa.mdf")>  _
        Public ReadOnly Property ficBddDonneesProd() As String
            Get
                Return CType(Me("ficBddDonneesProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\bddAgumaaa.mdf")>  _
        Public ReadOnly Property ficBddDonneesTest() As String
            Get
                Return CType(Me("ficBddDonneesTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Documents\BacASable\bddAgumaaa.mdf")>  _
        Public ReadOnly Property AttachDbFilenameTest() As String
            Get
                Return CType(Me("AttachDbFilenameTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Gestion\Trésorerie\Comptabilité\Eléments comptables\Chèques\"& _ 
            "")>  _
        Public ReadOnly Property repChqProd() As String
            Get
                Return CType(Me("repChqProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Gestion\Trésorerie\Comptabilité\Eléments comptables\Chèques\"& _ 
            "")>  _
        Public ReadOnly Property repChqTest() As String
            Get
                Return CType(Me("repChqTest"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(";Integrated Security=True;Connect Timeout=30")>  _
        Public ReadOnly Property ParamDb() As String
            Get
                Return CType(Me("ParamDb"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=")>  _
        Public ReadOnly Property DataSource() As String
            Get
                Return CType(Me("DataSource"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ficRelevéTraité.txt")>  _
        Public ReadOnly Property ficRelevéTraité() As String
            Get
                Return CType(Me("ficRelevéTraité"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\événement.ini")>  _
        Public ReadOnly Property ficEvénement() As String
            Get
                Return CType(Me("ficEvénement"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ressources\type.ini")>  _
        Public ReadOnly Property ficType() As String
            Get
                Return CType(Me("ficType"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://api.mistral.ai/v1/chat/completions")>  _
        Public ReadOnly Property urlMistral() As String
            Get
                Return CType(Me("urlMistral"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\ressources")>  _
        Public ReadOnly Property repFichierBilan() As String
            Get
                Return CType(Me("repFichierBilan"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT * FROM Mouvements;")>  _
        Public ReadOnly Property reqSelectToutMouvements() As String
            Get
                Return CType(Me("reqSelectToutMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Mouvements WHERE dateMvt = @dateMvt AND montant = @montant A"& _ 
            "ND sens = @sens;")>  _
        Public ReadOnly Property reqNbMouvements() As String
            Get
                Return CType(Me("reqNbMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT [imageChq] FROM [dbo].Cheque WHERE [id] = @id")>  _
        Public ReadOnly Property reqImagesChq() As String
            Get
                Return CType(Me("reqImagesChq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT [nom], [prenom], [raisonSociale] FROM [dbo].Tiers")>  _
        Public ReadOnly Property reqIdentiteTiers() As String
            Get
                Return CType(Me("reqIdentiteTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT categorieDefaut FROM Tiers where id = '")>  _
        Public ReadOnly Property reqCategoriesDefautMouvements() As String
            Get
                Return CType(Me("reqCategoriesDefautMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM Categorie WHERE debit = @debit;")>  _
        Public ReadOnly Property reqCategorie() As String
            Get
                Return CType(Me("reqCategorie"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM SousCategorie where idCategorie = @idCategorie;")>  _
        Public ReadOnly Property reqSousCategorie() As String
            Get
                Return CType(Me("reqSousCategorie"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, nom, prenom, raisonSociale, categorieDefaut, sousCategorieDefaut FROM "& _ 
            "Tiers;")>  _
        Public ReadOnly Property reqIdentiteCatTiers() As String
            Get
                Return CType(Me("reqIdentiteCatTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, numero, date, emetteur, destinataire FROM Cheque WHERE montant = @mont"& _ 
            "ant;")>  _
        Public ReadOnly Property reqChq() As String
            Get
                Return CType(Me("reqChq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id,nom, prenom FROM Tiers where nom is not null;")>  _
        Public ReadOnly Property reqIdentitePPTiers() As String
            Get
                Return CType(Me("reqIdentitePPTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id,raisonSociale FROM Tiers where raisonSociale is not null;")>  _
        Public ReadOnly Property reqIdentitePMTiers() As String
            Get
                Return CType(Me("reqIdentitePMTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT idDoc, dateDoc, contenuDoc, cheminDoc, categorieDoc, sousCategorieDoc, idM"& _ 
            "vtDoc FROM [dbo].[Documents];")>  _
        Public ReadOnly Property reqDocs() As String
            Get
                Return CType(Me("reqDocs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT libelle FROM SousCategorie where idCategorie =")>  _
        Public ReadOnly Property reqLibelleSousCategorie() As String
            Get
                Return CType(Me("reqLibelleSousCategorie"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT sousCatégorie, SUM(montant) FROM Mouvements WHERE catégorie = @category GR"& _ 
            "OUP BY sousCatégorie ORDER BY SUM(montant) DESC;")>  _
        Public ReadOnly Property reqSommeCatMouvements() As String
            Get
                Return CType(Me("reqSommeCatMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT sousCatégorie, sum(montant) FROM Mouvements where catégorie = '")>  _
        Public ReadOnly Property reqSommeSousCatMouvements() As String
            Get
                Return CType(Me("reqSommeSousCatMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select Id , catégorie, sousCatégorie, montant , sens , tiers , note , dateMvt , d"& _ 
            "ateCréation , dateModification , etat , événement , type , modifiable , numeroRe"& _ 
            "mise , idCheque from Mouvements;")>  _
        Public ReadOnly Property sqlSelectMouvements() As String
            Get
                Return CType(Me("sqlSelectMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3rD/s9+aP2fG4h5jK7lMnO=")>  _
        Public ReadOnly Property selAleatoire() As String
            Get
                Return CType(Me("selAleatoire"),String)
            End Get
        End Property
        
        '''<summary>
        '''Procécdure stockée d&apos;identification des mouvements déjà saisis
        '''</summary>
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Configuration.SettingsDescriptionAttribute("Procécdure stockée d'identification des mouvements déjà saisis"),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT Id, catégorie, sousCatégorie, montant, sens, tiers, note, dateMvt, dateCré"& _ 
            "ation, dateModification, etat, événement, type, modifiable, numeroRemise, idCheq"& _ 
            "ue FROM [dbo].[Mouvements] WHERE dateMvt = @dateMvt AND montant = @montant AND s"& _ 
            "ens = @sens;")>  _
        Public ReadOnly Property procMvtsIdentiques() As String
            Get
                Return CType(Me("procMvtsIdentiques"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EXEC dbo.ObtenirMouvementsSimilaires @dateMvt, @montant, @sens")>  _
        Public ReadOnly Property procMvtsIdentiquesEX() As String
            Get
                Return CType(Me("procMvtsIdentiquesEX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Mouvements] SET [catégorie] = @Categorie, [sousCatégorie] = @SousCa"& _ 
            "tegorie, [tiers] = @Tiers, [note] = @Note, [dateModification] = GETDATE(), [etat"& _ 
            "] = @Etat, [événement] = @Evenement, [type] = @Type, [modifiable] = @Modifiable,"& _ 
            " [numeroRemise] = @NumeroRemise where [Id] = @Id")>  _
        Public ReadOnly Property updMvt() As String
            Get
                Return CType(Me("updMvt"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gestionTresorerie\monFichier.docx")>  _
        Public ReadOnly Property ficBilan() As String
            Get
                Return CType(Me("ficBilan"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Mouvements] (note, catégorie, sousCatégorie, tiers, dateCréati"& _ 
            "on, dateMvt, montant, sens, etat, événement, type, modifiable, numeroRemise, idC"& _ 
            "heque) VALUES (@note, @categorie, @sousCategorie, @tiers, @dateCréation, @dateMv"& _ 
            "t, @montant, @sens, @etat, @événement, @type, @modifiable, @numeroRemise, @idChe"& _ 
            "que);")>  _
        Public ReadOnly Property insertMvts() As String
            Get
                Return CType(Me("insertMvts"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE Mouvements SET idCheque = @nouvelIdCheque WHERE Id = @idMouvement")>  _
        Public ReadOnly Property updMvtIdChq() As String
            Get
                Return CType(Me("updMvtIdChq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM Categorie")>  _
        Public ReadOnly Property reqCategorieTout() As String
            Get
                Return CType(Me("reqCategorieTout"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Mouvements] WHERE [Id] = @Id")>  _
        Public ReadOnly Property delMvt() As String
            Get
                Return CType(Me("delMvt"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("select Id , (select libelle from Categorie where id = catégorie) as Catégorie, (s"& _ 
            "elect libelle from sousCategorie where id = sousCatégorie) as sousCatégorie, mon"& _ 
            "tant , CASE sens WHEN 1 THEN 'Crédit' ELSE 'Débit' END as 'Sens', (select coales"& _ 
            "ce(nom + ' ' + prenom, raisonSociale ) from Tiers where id = tiers) as Tiers, no"& _ 
            "te, dateMvt, dateCréation, dateModification, etat, événement, type, CASE modifia"& _ 
            "ble WHEN 1 THEN 'modifiable' ELSE 'Non modifiable' END as 'Modifiable', numeroRe"& _ 
            "mise, idCheque from Mouvements;")>  _
        Public ReadOnly Property sqlSelectMouvementsLibelles() As String
            Get
                Return CType(Me("sqlSelectMouvementsLibelles"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\Mon Drive\AGUMAAA\Gestion\Trésorerie\Comptabilité\Bdd\bddAgumaaaProd.mdf")>  _
        Public ReadOnly Property AttachDbFilenameProd() As String
            Get
                Return CType(Me("AttachDbFilenameProd"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Comptes] WHERE [login] = @login")>  _
        Public ReadOnly Property delCompte() As String
            Get
                Return CType(Me("delCompte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Comptes] SET [motDePasse] = @motDePasse WHERE [login] = @login")>  _
        Public ReadOnly Property updCompte() As String
            Get
                Return CType(Me("updCompte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Comptes] ([login], [motDePasse], [typeAcces]) VALUES (@login, "& _ 
            "@motDePasse, @typeAcces)")>  _
        Public ReadOnly Property insertCompte() As String
            Get
                Return CType(Me("insertCompte"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].Cheque ([numero], [date], [emetteur], [montant], [banque], [des"& _ 
            "tinataire], [imageChq]) VALUES (@numero, @date, @emetteur, @montant, @banque, @d"& _ 
            "estinataire, @imageChq);")>  _
        Public ReadOnly Property insertChq() As String
            Get
                Return CType(Me("insertChq"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UPDATE [dbo].[Documents] SET dateDoc = @dateDoc, contenuDoc = @contenuDoc, chemin"& _ 
            "Doc = @cheminDoc, categorieDoc = @categorieDoc, sousCategorieDoc = @sousCategori"& _ 
            "eDoc, idMvtDoc=@idMvtDoc WHERE idDoc = @idDoc;")>  _
        Public ReadOnly Property updDocs() As String
            Get
                Return CType(Me("updDocs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DELETE FROM [dbo].[Documents] WHERE idDoc = @idDoc"&Global.Microsoft.VisualBasic.ChrW(9)&";")>  _
        Public ReadOnly Property delDocs() As String
            Get
                Return CType(Me("delDocs"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, nom, prenom FROM Tiers WHERE nom IS NOT NULL;")>  _
        Public ReadOnly Property selTiersPhysique() As String
            Get
                Return CType(Me("selTiersPhysique"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, raisonSociale FROM Tiers WHERE raisonSociale IS NOT NULL;")>  _
        Public ReadOnly Property selTiersMorale() As String
            Get
                Return CType(Me("selTiersMorale"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT id, libelle FROM Categorie;")>  _
        Public ReadOnly Property selIdLibCat() As String
            Get
                Return CType(Me("selIdLibCat"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Tiers WHERE (nom = @nom AND prenom = @prenom and raisonSocia"& _ 
            "le is null) OR raisonSociale = @raisonSociale and nom is null AND prenom is null"& _ 
            ";")>  _
        Public ReadOnly Property cptTiers() As String
            Get
                Return CType(Me("cptTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT sousCategorieDefaut FROM Tiers where id = @id;")>  _
        Public ReadOnly Property reqSousCategoriesDefautMouvements() As String
            Get
                Return CType(Me("reqSousCategoriesDefautMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO [dbo].[Documents] (dateDoc, contenuDoc, cheminDoc, categorieDoc, sous"& _ 
            "CategorieDoc, idMvtDoc) VALUES (@dateDoc, @contenuDoc, @cheminDoc, @categorieDoc"& _ 
            ", @sousCategorieDoc, @idMvtDoc);")>  _
        Public ReadOnly Property insertDocAgumaaa() As String
            Get
                Return CType(Me("insertDocAgumaaa"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT libelle from categorie where id in (select catégorie FROM Mouveme"& _ 
            "nts);")>  _
        Public ReadOnly Property reqCategoriesMouvements() As String
            Get
                Return CType(Me("reqCategoriesMouvements"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM Tiers WHERE (nom = @nom AND prenom = @prenom) OR raisonSocia"& _ 
            "le = @raisonSociale);")>  _
        Public ReadOnly Property selExisteTiers() As String
            Get
                Return CType(Me("selExisteTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSERT INTO Tiers (nom, prenom, raisonSociale, categorieDefaut, sousCategorieDefa"& _ 
            "ut, dateCreation, dateModification) VALUES (@nom, @prenom, @raisonSociale, @cate"& _ 
            "gorieDefaut, @sousCategorieDefaut, @dateCreation, @dateModification);")>  _
        Public ReadOnly Property insertTiers() As String
            Get
                Return CType(Me("insertTiers"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("parametresAppli.json")>  _
        Public ReadOnly Property parametresJson() As String
            Get
                Return CType(Me("parametresJson"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.gestionTresorerie.My.MySettings
            Get
                Return Global.gestionTresorerie.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
