insert into SousCategorie (id, libelle, dateDebut, dateFin) values (1 ,'Achat de petits materiels & equipements',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (2 ,'Achats de logiciels',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (3 ,'Achats de marchandises (pour revente)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (4 ,'Fournitures de bureau',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (5 ,'Fournitures diverses',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (6 ,'Fournitures imprimante',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (7 ,'Fournitures informatiques',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (8 ,'Cheque a ventiler (a preciser) ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (9 ,'Cotisation annuelle ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (10,'Paiement mensuel ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (11,'sations et licence versees]',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (12,'Cotisations a l instance Nationale ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (13,'Cotisations diverses versees ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (14,'Cotisations et licences versees (a preciser)',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (15,'Licences versees pour les membres ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (16,'AIST43 A decrire',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (17,'Prevoyance (Malakof Mederic) ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (18,'Retraite (Klesia) ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (19,'URSSAF ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (20,'La Comedie de Saint-Etienne ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (21,'SACEM ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (22,'Deplacements, missions et receptions (a preciser) ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (23,'Frais de deplacements  ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (24,'Frais de pots (AG, ...)  ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (25,'Frais de restaurants  ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (26,'Frais d hebergements',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (27,'Entretien et reparation des locaux ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (28,'Entretien et reparation des materiels ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (29,'Entretiens et reparations (a preciser) ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (30,'Materiel : AFC ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (31,'Menage : intervention de l ADMR lors d une absence d Amandine',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (32,'Frais de personnel interne ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (33,'Frais de personnel interne (a preciser) ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
insert into SousCategorie (id, libelle, dateDebut, dateFin) values (34,'Remunerations d Amandine ',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);